### ISSUE TITLE
1.20.1 Issues

### ISSUE THREAD

**Issue by TheBiggestHuman** [Sploder12/Potioncraft#6] opened 2024-08-14 19:02 UTC
Hello! Thank you for the mod, it works really well and makes making potions a whole lot more interesting than vanilla game.
I have found several issues, unsure if you know of them already, but I will report them here anyways.

So, a major issue I found is that the v0.5.0 of the mod for 1.20.1 just doesn't work, at all. In a new instance of fabric, with only the fabric API and this mod, you just can't put any potion in the cauldron.

I have found a balancing issue in the older versions, specifically v0.4.1, where adding a single redstone to a potion of harming in the cauldron makes it have a duration, which is quite powerful.

That is all I have found so far, aside from them I really love the mod and it feels like what brewing should have been. Thank you so much!

**Comment by Sploder12** [comment] 2024-08-14 19:37
Thank you for the feedback! I was not aware of these issues before, I will work on fixing them once I'm back home from vacation (didn't bring a laptop with me). I'm expecting August 20th to be when I'm able to release a patch.

The v0.5.0 issue is odd, I must've missed it during testing somehow. It should be easy to track since that's a major issue, but if you could post a log file from when it wasn't working that would make it even easier!

I can see how that'd be unbalanced! I'll add some code to keep instant effects instant.

I'm glad you're enjoying it! I'll have that patch out as soon as possible!

**Comment by TheBiggestHuman** [comment] 2024-08-15 09:07
Here is the log, it definitely shows an error of some sort with this mod
[latest.log](https://github.com/user-attachments/files/16623554/latest.log)

Thank you so much!

**Comment by Sploder12** [comment] 2024-08-15 09:48
Thank you, the log sped up finding the root cause greatly! I've identified the issue based off the log, and yeah, that'd definitely break it! Looks like I missed it since the dev environment doesn't behave exactly the same.

**Comment by Sploder12** [comment] 2024-08-19 13:10
A fix has been released as v0.5.1! Thank you again for your feedback and the log!

**Closed by Sploder12** 2024-08-19 13:10 UTC
